### ISSUE TITLE
Implement Iframe mode

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/website#14]
Remove the website navbar if the variable iframe=true  comes within the query-string.

This should be on any view, including /assets

**Comment by Camilocoo** [comment]
this one works locally but I'm struggling to make it work on production

**Comment by alesanchezr** [comment]
que es lo que no te funciona en produccin?

**Comment by Camilocoo** [comment]
Listo ya te mande el PR

**Comment by Camilocoo** [comment]
no con este nose que sucede no sirve en production , iba a intentar con el truco que me ensenaste para ver si estoy trabajando con la version correcta , pero como este esta en gatsby no supe como hacerlo aca
