### ISSUE TITLE
Instalar tagmanager

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/website#15]

**Comment by Camilocoo** [comment]
ya esa instalado pero no le he puesto los private keys

**Comment by alesanchezr** [comment]
mm... no entiendo bien. Cuales private keys?

Hiciste un PR con esto?

**Comment by Camilocoo** [comment]
Listo

**Comment by alesanchezr** [comment]
Recuerda tambien isntalar:
- [x] student.breatheco.de
- [x] teacher.breatheco.de
- [x] admin.breatheco.de
- [x] projects.breatheco.de

**Comment by Camilocoo** [comment]
listo ya todos los probe menos el de projects porque en ese solo se pueden ver los tags en production me avisas si sirve cuando le hagas merge
