### ISSUE TITLE
Redirects for Google

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/website#16]
1. `https://breatheco.de/en/assets/` -> `https://breatheco.de/assets/`
2. `https://breatheco.de/en/lesson-asset/command-line-or-bash-cheat-sheet/` -> `https://breatheco.de/lesson/command-line-or-bash-cheat-sheet/`

**Comment by Camilocoo** [comment]
Listo

**Comment by Camilocoo** [comment]
listo ya quedo bien
