### ISSUE TITLE
Nueva vista para single asset

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/website#27]
![Screen Shot 2019-06-03 at 12 47 40 PM](https://user-images.githubusercontent.com/426452/58819286-e82d1700-85fd-11e9-809a-02f96fb4d885.png)

El boton para "view website" solo debe aparecer para los asseets que tengan un separate website, (por ejemplo los cheat sheets no tienen, pero los canales de youtube si).

El boton de download solo debe aparecer para tipos de assets se puedan descargar.

Acuerdate de implementar los redirects de URL los assets viejos que estaban en el wordpress a estos nuevos.

**Comment by Camilocoo** [comment]
listo esto ya quedo @alesanchezr
