### ISSUE TITLE
Filtros por defecto y en los URL

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/website#30]
- Si entro a https://breatheco.de/`en`/lessons debe cargar las lessons y assets en ingles por defecto en otras palabras, el filtro de idioma debe tener ingles pre-seleccionado.
- Lo mismo pasa si lo pongo en español https://breatheco.de/`es`/lessons
- Lo mismo pasa en la vista de assets solos https://breatheco.de/`en`/assets

**Comment by Camilocoo** [comment]
listo @alesanchezr
