### ISSUE TITLE
Hay topicos repetidos

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/website#41]
- Cheat Sheets es lo mismo que Cheat Sheet
- youtube no es lo mismo que video? 
- Que significa responsive desgin?

![Screen Shot 2019-06-21 at 2 22 45 PM](https://user-images.githubusercontent.com/426452/59943368-0f724980-9430-11e9-93c2-5f9dcf7941ad.png)

**Comment by Camilocoo** [comment]
+ dale ya corrijo cheat sheet .

+ no no es lo mismo pq videos son videos y youtube es una plataforma de videos, pero ese filtro le hace eso mas referencia a canales de youtube entoces si quieres lo cambio mejor a youtube channel para ser mas especifico 

+ responsive design  es una filosofía de diseño y desarrollo cuyo objetivo es adaptar la apariencia de las páginas web al dispositivo que se esté utilizando para visitarlas. entonces ese filtro debe hacer referencia a assets que tengan que ver con responsive design 

@alesanchezr

**Comment by Camilocoo** [comment]
listo a este ya le arregle los filtros repetidos y los puse mas especificos
