### ISSUE TITLE
404 cuando le doy a view website

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/website#42]
Si le das a view website en este asset da 404

https://breatheco.de/lesson/bootstrap-sizes-in-media-query

**Comment by Camilocoo** [comment]
si dame el link a donde quieres que redirija eso o el cheatsheet pq lo unico que tenia eso era esa imagen @alesanchezr

**Comment by alesanchezr** [comment]
Hay que buscar una pagina que tenga esos bootstrap siszes in media query

**Comment by alesanchezr** [comment]
si queies elimina este resource.

**Comment by Camilocoo** [comment]
@alesanchezr dale
